name: Build site

on:
  push:
    branches: [ build-action ]

env:
  PUB_BRANCH: publish

jobs:
  run-build-script:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: build-action

      - name: Create New Branch
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git branch -f $PUB_BRANCH
          git checkout $PUB_BRANCH

      - name: Run Build Script
        run: |
          npm install
          npm run build
          rm .gitignore
          git add .
          git commit -m ":rocket: Compile site"

      - name: Set submodules to track publish branch
        run: |
          while IFS= read -r submodule; do
              git submodule set-branch -b $PUB_BRANCH -- "$submodule"
          done <<< "$submodules"
          git add .gitmodules
          git commit -m ":package: Submodules track publish branch"

      - name: Push changes
        run: |
          git push -uf origin $PUB_BRANCH